### ISSUE TITLE
Enhancement: Choose a list to move subscribers to after cancelling membership

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-mailchimp#111]
Related to this topic: https://www.paidmembershipspro.com/forums/topic/mailchimp-and-expired-cancelled-members/

Current Behavior:
- When a membership expires, they're unsubscribed from the list they were in

Expected Behavior:
- Allow admins to choose if a member should be moved to 'Non-Members' list in MC
- Once a membership expires, unsubscribe them from the original list and assign them to the 'Non-Members' list

**Comment by dparker1005** [comment]
This can be accomplished using the "Non-Member Audiences" setting.
