### ISSUE TITLE
Can't see more than 15 Mailchimp lists (of 23)

### ISSUE THREAD

**Issue by wbgraphics** [strangerstudios/pmpro-mailchimp#123]
I've set up Mailchimp API keys on my two websites, but I cant see more than 15 Mailchimp lists on both of them. Is there any way to see all lists without the 15 limit?

**Comment by wbgraphics** [comment]
I've found out that it can be changed in "classes/class-pmpromc-mailchimp-api.php" file, line 104:
`$max_lists = apply_filters('pmpro_addon_mc_api_fetch_list_limit', 15);`
This isn't a very good way as it will be overwritten with every uplate or PMPro Mailchimp plugin.
Can it be applied in WP theme functions.php file or in pmpro-customizations.php file?
If yes, then how?

I've foud this hook on PMPro website:
`apply_filters( 'pmpro_addon_mc_api_fetch_list_limit', int $limit );`
but I have no idea how to use it.

**Comment by dparker1005** [comment]
Hi @wbgraphics,

We have a code recipe here that shows how to use that filter to set the number of lists that are shown:
https://gist.github.com/andrewlimaza/da44c73ea7811549023803100b99686a

Please let me know if you run into any issues while using that code recipe on your site.

**Comment by wbgraphics** [comment]
Hi @dparker1005,
Thank you very much!
