### ISSUE TITLE
Export a CSV for your Mailchimp Import returns empty results

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-mailchimp#143]
Steps to replicate
1. Navigate to /wp-admin/options-general.php?page=pmpromc_options
2. Select a level and export
3. No data is found

Tested this with the fix used in #139 however the same issue occurs

Tested with PMPro 3.0.4 and PMPro Mailchimp 2.3.6

**Comment by kimcoleman** [comment]
We believe this is resolved in #139 - tested locally and fixed.
