### ISSUE TITLE
No lists and no errors showing after entering API Key

### ISSUE THREAD

**Issue by jbruggeling** [strangerstudios/pmpro-mailchimp#23]
Having issues getting the new plugin to pass data to the API.

Several reported issues on word press.org
https://wordpress.org/support/topic/no-lists-found-after-entering-api?replies=4#post-8733545

Attempted complete code removal and reinstall no success. 1.x versions work 2.x versions Fail

Also the code base appears to be on a older API. MailChimp is only going to support API v4 come 2017 and it looks like the API code base for this plugin is on a earlier version.

**Comment by eighty20results** [comment]
There's no API v4 that I'm aware of. There's a v3 which is scheduled to become the only supported API at the end of 2016. The PMPro MailChimp add-on uses.

Have you validated that the API key doesn't contain any extra leading/trailing spaces?

**Comment by jbruggeling** [comment]
Just went and reinstalled the plugin and it failed to load the mailchimp lists despite not complaining about the API Key. Proceeded to intentionally give a invalid API key which threw up some CURL errors. Put the correct API key back in and working. Weird - glitch in the matrix feel free to close.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
