### ISSUE TITLE
Limited to 15 Mailchimp lists

### ISSUE THREAD

**Issue by patrickjc** [strangerstudios/pmpro-mailchimp#24]
Is there a reason why this plugin limits the lists pulled through for the API to 15?

I am building a site for a client who has around 50 lists in mailchimp and as a result the one created specifically for the members is not showing.

Is there anyway around this or is it set this way to stop too many calls to the API or something?

**Comment by patrickwurk** [comment]
Got it sorted.

**Comment by patrickjc** [comment]
Got it sorted.
