### ISSUE TITLE
Deselecting chosen opt-in mail list cannot be done

### ISSUE THREAD

**Issue by jasperf** [strangerstudios/pmpro-mailchimp#27]
I have selected an opt-in MailChimp list for on checkout on options-general.php?page=pmpromc_options but now we no longer want it. We want zero lists. Seems though I can only deselect one by selecting another. How can this be done? Seems like a bug to me.

**Comment by deerickson** [comment]
I have the same damn problem. Can't figured it out. Ugh.

**Comment by moubarat** [comment]
I too am facing the same problem...I don't want to select any opt-in . Please fix this.

**Comment by moubarat** [comment]
There should be an option ...where I select if I want to display the opt in list or not.

**Comment by deerickson** [comment]
It's a bug that only effects Mac users. I fixed it by deselecting from a Windows machine.

**Comment by jasperf** [comment]
I was able to deselect by changing the source code (html). Do hope they fix the problem soon. That it only affects Max users I find hard to believe. But have not had time to test on a Windows Virtual Machine. Hope they'll fix it soon.

**Comment by deerickson** [comment]
Believe what you want. All I can tell you is it worked for me on a Windows
machine.

David Erickson
*VOICE:* 651.400-0066
*SOCIAL:* Facebook <http://facebook.com/david.erickson> | Twitter
<http://twitter.com/derickson> | LinkedIn
<http://www.linkedin.com/in/davideerickson> | Google+
<https://google.com/+DavidErickson> | YouTube
<http://www.youtube.com/davideerickson> | Flickr
<http://www.flickr.com/people/daviderickson/>
Pinterest <http://pinterest.com/deerickson/> | Slideshare
<http://www.slideshare.net/derickson>
-- 
<http://e-Strategy.com/>
e-Strategy Blog <http://Trends.e-StrategyBlog.com/> | e-Strategy Trends
<http://Trends.e-StrategyBlog.com/> | e-Strategy TV <http://eStrategy.tv/>
@e_Strategy <http://twitter.com/e_Strategy> | @TheDailyNumbers
<http://twitter.com/TheDailyNumbers>
LinkedIn <http://www.linkedin.com/groups/eStrategy-1103667> | Facebook
<http://facebook.com/estrategycom> | YouTube
<http://youtube.com/user/estrategy>

**Comment by moubarat** [comment]
Thanks deerickson,

I work on Windows ...

I tried using firefox...I couldn't deselect

I tried Chrome...and IT WORKED :)

**Comment by moubarat** [comment]
Has anyone faced issues with PayPal Express Add On ?

**Comment by jasperf** [comment]
@moubarat Better open another issue for that.

**Comment by deerickson** [comment]
Weird that it would be a browser-specific issue on such a mundane element
as a multi-selection box. Glad you got it resolved. :-)

David Erickson
*VOICE:* 651.400-0066
*SOCIAL:* Facebook <http://facebook.com/david.erickson> | Twitter
<http://twitter.com/derickson> | LinkedIn
<http://www.linkedin.com/in/davideerickson> | Google+
<https://google.com/+DavidErickson> | YouTube
<http://www.youtube.com/davideerickson> | Flickr
<http://www.flickr.com/people/daviderickson/>
Pinterest <http://pinterest.com/deerickson/> | Slideshare
<http://www.slideshare.net/derickson>
-- 
<http://e-Strategy.com/>
e-Strategy Blog <http://Trends.e-StrategyBlog.com/> | e-Strategy Trends
<http://Trends.e-StrategyBlog.com/> | e-Strategy TV <http://eStrategy.tv/>
@e_Strategy <http://twitter.com/e_Strategy> | @TheDailyNumbers
<http://twitter.com/TheDailyNumbers>
LinkedIn <http://www.linkedin.com/groups/eStrategy-1103667> | Facebook
<http://facebook.com/estrategycom> | YouTube
<http://youtube.com/user/estrategy>

**Comment by andrewlimaza** [comment]
I've tested this with version 2.1 on Mac (using Chrome).

To deselect a list CMD + Left click deselects lists. Once deselected save your options.

I hope this helps, not sure if this issue is still present for you guys :)

**Comment by Bobz-zg** [comment]
Helps.
These should be replaced by checkboxes.

**Comment by dparker1005** [comment]
The select field used to choose audiences have been replaced with checkboxes in the most recent version of PMPro Mailchimp, which should help to clear up some confusion around de-selecting audiences.

We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
