### ISSUE TITLE
Screws with other mailchimp software

### ISSUE THREAD

**Issue by lukegw** [strangerstudios/pmpro-mailchimp#3]
The theme I am using (SweetDateWP - which is built on using the PM Pro plugin).

I receive this error when using its newsletter sign up form.

Fatal error: Cannot redeclare class MCAPI in /wp-content/themes/sweetdate/framework/widgets/mailchimp/MCAPI.class.php on line 3

Is this a theme error or plugin error - you never replied to my other post a month ago about the plugin screwing up the widgets area in wordpress.

**Comment by dparker1005** [comment]
Class name was changed to `PMPromc_Mailchimp_API` to resolve this issue
