### ISSUE TITLE
listsubscribe wrong # args

### ISSUE THREAD

**Issue by hbrock25** [strangerstudios/pmpro-mailchimp#32]
fills logs with:

PHP Warning:  Missing argument 3 for pmpromc_pmpro_mailchimp_listsubscribe_fields() in /usr/share/nginx/hcacademy/wp-content/plugins/pmpro-mailchimp/pmpro-mailchimp.php on line 1307

**Comment by strangerstudios** [comment]
Thank you! Fixed in recent commits.
