### ISSUE TITLE
2.1.1 fails to "even attempt to access MailChimp API"

### ISSUE THREAD

**Issue by michelestern** [strangerstudios/pmpro-mailchimp#38]
I just installed pmpro Version 1.9.4.1 with pmpro-mailchimp 2.1.1.

When I attempt to enter the mailchimp API I get the following error: 

**Sorry, but MailChimp was unable to verify your API key. MailChimp gave this response:
**401: API Key Invalid. Detail: Your API key may be invalid, or you've attempted to access the wrong datacenter.
Please try entering your API key again.****

I checked with MailChimp to see what was happening on their end. They said:
"I don't even see an attempt to access our API on the backend... usually we would see a call coming in and then failing for a number of reasons but the call log is blank."

Some notes:
- I first attempted to use an existing api, and when that did not work, I created a new one. Same results.
- I deleted the plug-ins and downloaded them from your website and reinstalled those in case there was some difference between that and the WP repository, no luck.
- I do have a Gravity Forms Mail Chimp add-on, but when I disable that, same thing.
- When I first installed this yesterday I had not updated Wordpress to 4.9 so I did that (now 4.9.1) and that did not help. In short, same issue with a 4.8 version and a 4.9 version of wp.
- This is a sub-site on multisite.

**Comment by andrewlimaza** [comment]
Are you still experiencing issues with this?

I have tested this and it works for me. However, I would recommend in testing this on a non-multisite and see if the issue persists.

I'd also recommend in reaching out to the PMPro team on www.paidmembershipspro.com :)

This way they will be able to work on the problem with you and come to a solution.

Hope this helps. :)

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
