### ISSUE TITLE
Only pulls in 15 lists

### ISSUE THREAD

**Issue by servesense** [strangerstudios/pmpro-mailchimp#39]
The plugin only pulls in 15 lists.  If there are more than 15 lists in the account, some are cut off, making them unavailable.

**Comment by nexus6nexus6** [comment]
+1

**Comment by dparker1005** [comment]
The number of lists that PMPro retrieves from Mailchimp can be changed using the `pmpro_addon_mc_api_fetch_list_limit` filter, which is demonstrated here: https://gist.github.com/andrewlimaza/da44c73ea7811549023803100b99686a
