### ISSUE TITLE
Formatting Improvements for the "Join our mailing list" section at checkout

### ISSUE THREAD

**Issue by kimcoleman** [strangerstudios/pmpro-mailchimp#46]
After our move to table-free checkout page, this Add On was not updated to reflect new core styling, specifically: https://github.com/strangerstudios/pmpro-mailchimp/blob/master/pmpro-mailchimp.php#L495-L508

Also, the "textdomain" should be updated in the translation strings from 'pmpro' to 'pmpro-mailchimp'.

**Comment by michaelbeil** [comment]
A request for this (ticket 422641 [moderators only):
>trying to update the text and style of the following test provided by the plugin Mailchimp ad on but can’t find were to fix it  
![image](https://user-images.githubusercontent.com/4752949/168900456-f2894078-75e6-4b4e-821c-e09050e49931.png)

**Comment by michaelbeil** [comment]
PR #127 fixes this. 
![image](https://user-images.githubusercontent.com/4752949/170350973-efd94804-c3f3-48cb-884e-eadeb4f0e5dd.png)
