### ISSUE TITLE
Allow user's to Opt-in at another point besides checkout

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-mailchimp#48]
A user would like the ability to allow members to opt-in to lists besides on the checkout page. This would need to include the user's membership level and pass it to MailChimp.

Maybe a shortcode that will allow user's to update their opt-in preferences that can be embedded or shown on the user's profile page?

**Comment by dparker1005** [comment]
Users can now also opt into Mailchimp audiences from their edit profile page.
