### ISSUE TITLE
cancelled members not deleted on mailchimp

### ISSUE THREAD

**Issue by leihan04** [strangerstudios/pmpro-mailchimp#5]
I was testing this and saw that if a member cancelled on my site,  the mailchimp list still keep them in the list.  Is this by design?

I would like for this plugin to delete the members from the mailchimp list as well if the member cancelled their subscription.  Is that possible?

thanks

Lei

**Comment by warrantbrent** [comment]
Hello,
I don't know what type of organization you have, but if it was me, I would like the cancelled member to remain in mailchimp so I can follow up with them, or perhaps have automations to try to regain their membership. Your question is in line with what I was hoping to have answered, which is if I have an annual member who expires or cancels, can we get their pmplevelid to change to something like 99 so we can segment them in mailchimp and start those follow up emails. It seems right now that once a person expires their annual, they remain the same pmplevelid and so mailchimp sees them as subscribed unless I manually reconcile them.
Thoughts?

**Comment by rafecolton** [comment]
It would be really useful to have a PMPSTATUS field that indicated user status. That would enable us to know that a user canceled while at the same time knowing what membership level they previously had.

**Comment by dparker1005** [comment]
We now have a setting `Unsubscribe on Level Change?` to optionally remove users from MC audiences when they lose a membership level.
