### ISSUE TITLE
Bug: MailChimp API sending DELETE requests for users

### ISSUE THREAD

**Issue by AnsieLima** [strangerstudios/pmpro-mailchimp#50]
MailChimp API seems to be sending DELETE requests for users, without members unsubscribing or being expired. I'm only aware of One user having this issue at the moment.  

The MailChimp API would use the PATCH or PUT method to update an existing subscriber, and they would need to be updating the `status` parameter from `subscribed` to `unsubscribed`. The documentation for that endpoint can be found here on the Edit tab:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#%20

**Comment by greathmaster** [comment]
Could be related… After a member has checked out and assigned to a MailChimp level, if an admin updates their email address on the WordPress "Edit Profile" page, MailChimp seems to delete the contact instead of updating the email address.

**Comment by messica** [comment]
When updating emails via the profile page, PMPro unsubscribes the user then subscribes them again.

[MailChimp returns a 204 status code (No Content) for successful DELETE requests](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#%20) but we check for 200 when unsubscribing, so the plugin thinks there was an error and doesn't continue to subscribe the user. 

Checking for 204 instead fixes this, but we should be using the member's status parameter instead.

I'm working on this now.

**Comment by messica** [comment]
https://github.com/strangerstudios/pmpro-mailchimp/pull/60 fixes the profile update issue but we should be updating the member status instead of deleting them when unsubscribing like @AnsieLima mentioned.

**Comment by dparker1005** [comment]
Users should now be set to `unsubscribed` status instead of being completely deleted from a Mailchimp audience as of v2.2.
