### ISSUE TITLE
FEATURE REQUEST: Inform admins if required MERGE fields in Mailchimp are not set from PMPro

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-mailchimp#58]
Invalid MERGE fields are a common reason users are not subscribed to a Mailchimp list. Usually, the MERGE field is set as "Required" in Mailchimp but not included in the data submitted at checkout. Mailchimp rejects such signups since the "Required" field is not set.

Similar case is if the MERGE field is included but is in the improper format. Mailchimp will also reject these sign ups.

We could look up the required MERGE fields and compare when a user checks out.

Resource: https://developer.mailchimp.com/documentation/mailchimp/reference/lists/merge-fields/

**Comment by messica** [comment]
I like this idea. Maybe we should do it at the same time we validate the MailChimp options:
https://github.com/strangerstudios/pmpro-mailchimp/blob/master/pmpro-mailchimp.php#L705
