### ISSUE TITLE
Bug: Firefox Only - Javascript in href for show #pmpromc_export_instructions faulty

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-mailchimp#62]
When using FireFox browser and user clicks on "Click here to export your members list for a MailChimp Import" button the returned URL in the address bar shows `javascript:jQuery('#pmpromc_export_instructions').show();` and page displays `[object Object]`

**Comment by ipokkel** [comment]
PR submitted to fix this FireFox specific issue: https://github.com/strangerstudios/pmpro-mailchimp/pull/63

**Comment by dparker1005** [comment]
Commit merged.
