### ISSUE TITLE
Feature Request: Support for MailChimp Segments and Tags

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-mailchimp#66]
With MailChimp doing away with audiences, a plus member has requested support for MailChimp segments and tags, including the ability to selectively send Register Helper fields as tags.

**Comment by tictag** [comment]
Further information on what's happening over at MailChimp and suggestions for bringing the MailChimp Add On in line is discussed in this thread: https://www.paidmembershipspro.com/forums/topic/feature-request-mailchimp-add-on-uses-tags/ and attached for convenience.

[MailChimp Add On Update.txt](https://github.com/strangerstudios/pmpro-mailchimp/files/3374974/MailChimp.Add.On.Update.txt)

Regards,
David
(_originator of this feature request_)

**Comment by dparker1005** [comment]
Closing in favor of #110, which contains a link to Mailchimp Developer docs for working with tags.
