### ISSUE TITLE
Is the a built-in way to capture First Name and send that to MailChimp?

### ISSUE THREAD

**Issue by BigPhilOV** [strangerstudios/pmpro-mailchimp#7]
Seems by default the PMP process captures the WP Username and Email. Awesome.
However, Mailchimp does not use the Username field. It wants First or Last name.
So at the moment, all I can automatically capture into Mailchimp is the email address. However, in my Mailchimp campaigns, I'd like to include the users name, as in "Hi Fred," instead of "Hi ,".

Currently the only work around is to use Autochimp by By Wanderer LLC Dev Team, which allows the WP Username field to be mapped to the MailChimp FNAME field. I then ask the MailChimp subscriber to check their First Name detail and edit it if they want.

I'd prefer a system that by default entered all the WP name fields and provided an easy mapping system into the MailChimp fields. I'm not a coder.

**Comment by dparker1005** [comment]
First and last names are now captured during PMPro checkout, which are then sent to Mailchimp when the user is subscribed.
