### ISSUE TITLE
Make sure unsubscribes are logged in the wp debug log like other events

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-mailchimp#78]
From customer celticwebdesign:

(1) With no audience selected in the `Non-member Users` setting, the cancelled member’s contact is archived on MailChimp
(2) No wp_debug log entry is made for this

The MailChimp Add On appears to log all other events, such as subscription events, but nothing is logged when a member is cancelled.

I believe all MailChimp events should be logged.

Steps To Recreate
(1) Ensure WordPress debugging is enabled
(2) Ensure no audience is selected in the `Non-member Users` MailChimp Add On settings
(3) Ensure a ‘Yes’ option is selected in the `Unsubscribe on Level Change?` MailChimp Add On settings
(4) Cancel a membership by selecting `None` in the `Current Level` of a member’s user profile
(5) Notice that the contact is archived on MailChimp
(6) Notice that no log entry is made in the wp_debug log

Further testing…
(7) Resubscribe the cancelled member, note that a wp_debug entry is correctly made

Plugin Information:
PHP v7.1.33
WordPress v5.4
PMPro v2.2
MailChimp Integration Add On v2.1.2

**Comment by dparker1005** [comment]
Resolved in v2.2.1 update
