### ISSUE TITLE
Autocomplete enabled causing new product checkout to not subscribe to mailchimp list

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-mailchimp#79]
A user reported that customers who check out via WooCommerce are not being subscribed to their Mailchimp list. I recreated this and can confirm that unchecking the `autocomplete` box and manually completing order subscribes me to my test mailing list.

**Comment by dparker1005** [comment]
As your test showed that completing the order successfully subscribed your user to your mailing list, I am going to close this ticket since we do not have specific steps to replicate this issue and other tests involving PMPro Mailchimp and PMPro WooCommerce have worked well.
