### ISSUE TITLE
Allow member email to be updated when they change this from their profile

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-mailchimp#88]
By default, PMPro Mailchimp Add On will subscribe a new email address every time it detects one, but what if an old member is changing their email address on file, let us see if we can get the API to just update their email instead of treating the member like a totally new contact to subscribe.

**Comment by tictag** [comment]
*For mods Only*
Further information, including step-by-step guide on re-creating issue and debug logs contained here: https://www.paidmembershipspro.com/forums/topic/bug-mailchimp-add-on-change-email-creates-new-contact/

**Comment by dparker1005** [comment]
Implemented in v2.3
