### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by bluecontent** [strangerstudios/pmpro-mailchimp#9]
Hello team, 

When activating this plugin I get the following fatal error: 

Fatal error: Call to a member function ping() on a non-object in /www/linkmm/mercur2015/mercur2015/blog/wp-content/plugins/pmpro-mailchimp/pmpro-mailchimp.php on line 76

And the whole site crashes. 
Am using Wordpress 4.1.1. 

Can you help?

**Comment by dparker1005** [comment]
This issue should be resolved.
