### ISSUE TITLE
BUG MailChimp Integration Add On: PHP Notice After Upgrading To v2.2.1

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-mailchimp#90]
After upgrading to MailChimp Integration Add On v2.2.1 I receive the following PHP Notice in my WP_DEBUG log:

[04-Feb-2020 03:51:16 UTC] PHP Notice: Trying to get property of non-object in /home/customer/www/dev.ksa-uk.net/public_html/wp/wp-content/plugins/pmpro-customizations/pmpro-customizations.php on line 617

The line referred to is:

` $user_info = get_userdata($user->ID);`

Prior to the upgrade, this notice was not logged.

Steps to Recreate:
1. Update to v2.2.1
2. Browse to Settings > PMPro MailChimp
3. Click “Click here to export your members list for a MailChimp Import”
4. Check WP_DEBUG log

https://www.paidmembershipspro.com/forums/topic/bug-mailchimp-integration-add-on-php-notice-after-upgrading-to-v2-2-1/

**Comment by dparker1005** [comment]
That PHP notice appears to be thrown from a PMPro Customizations file, not the PMPro Mailchimp Integration Add On. If you would like help in determining exactly what is causing this notice to be logged, please <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we can help you further there.

**Comment by tictag** [comment]
This was originally submitted to the PMPro Support Forum (the link is provided above) and one of your colleagues (Femi) decided to transfer the ticket to GitHub. You are now essentially transferring it back again.

I'm guessing that this bug has been fixed as I have not noticed any issues in my debug log (and therefore can be closed), but I would not expect support requests from a PMPro Plus members to be managed like this.

**Comment by dparker1005** [comment]
Hello @tictag, I sincerely apologize for closing this ticket too hastily. After reviewing your original ticket more closely and diving into the CSV Export code used in PMPro Mailchimp, I noticed an underlying issue that may have been causing the PHP warning in your customizations plugin that you were seeing in your error log. As a precaution, I have submitted a Pull Request (#112) which should address this issue if it is still occurring on your site.

If you are able to trigger that PHP warning to show again on your site, please feel free to test the fix I linked to above and let me know if you experience any issues with that fix.

**Comment by tictag** [comment]
np, David. I'm due to update my websites soon, next few days, so I'll re-test and let you know. Thanks for re-opening and looking into this :-)
