### ISSUE TITLE
BUG: MailChimp Add On – "&" In Names Are Not Handled Very Well

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-mailchimp#92]
When an “&” is contained within the First Name field, this is not handled very well when being transferred over to MailChimp. Please see screenshots.

![image](https://user-images.githubusercontent.com/22073464/74682676-6141be00-51cf-11ea-9be8-0403a1462838.png)
![image](https://user-images.githubusercontent.com/22073464/74682689-6a328f80-51cf-11ea-9ac1-79aecaa4f6d9.png)

**Comment by tictag** [comment]
For **MODS** Only
Further information in ticket: https://www.paidmembershipspro.com/forums/topic/bug-mailchimp-add-on-in-names-are-not-handled-very-well/

**Comment by tictag** [comment]
Any chance this could also be hooking into David Parker's v2.3 milestone? Just clears another one off my Trello board! Not urgent, though.

**Comment by dparker1005** [comment]
Fixed in v2.3
